In [17]:
import pandas as pd
import glob

# Combine all pitch logs into 1 big dataframe
files = glob.glob("pitch_logs/**/*.csv", recursive=True)
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

len(df)

/var/folders/lr/9t8mdvqx6_58bf8fjvwdbh3h0000gp/T/ipykernel_41824/1812518584.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

7616367

In [18]:
df.columns

Index(['Unnamed: 0', 'year', 'pitchingTeamId', 'pitchingTeam', 'conference',
       'hittingTeamId', 'hittingTeam', 'gameId', 'gameDate', 'inning', 'balls',
       'strikes', 'outs', 'pitcherId', 'Pitcher', 'pitcherHand', 'pitchType',
       'batterHand', 'plateLocX', 'plateLocZ', 'inducedVertBreak', 'horzBreak',
       'extension', 'pitchResult', 'atbatResult', 'relX', 'relZ',
       'releaseVelocity', 'spinRate', 'spinDir', 'rv'],
      dtype='object')

In [19]:
pd.set_option('display.max_columns', None)
df.head()

,Unnamed: 0,year,pitchingTeamId,pitchingTeam,conference,hittingTeamId,hittingTeam,gameId,gameDate,inning,balls,strikes,outs,pitcherId,Pitcher,pitcherHand,pitchType,batterHand,plateLocX,plateLocZ,inducedVertBreak,horzBreak,extension,pitchResult,atbatResult,relX,relZ,releaseVelocity,spinRate,spinDir,rv
0,0,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,0,0,0,1196833025,R. O'Connor,R,SI,R,0.49434,2.52535,5.98516,14.86544,5.56639,SL,K,-2.17982,4.97129,89.08355,2069.619596,251.856227,-0.15
1,1,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,0,1,0,1196833025,R. O'Connor,R,FC,R,1.93029,2.56696,2.29658,-0.51043,5.72107,B,K,-1.96659,5.40817,87.28152,2438.897149,157.768823,0.13
2,2,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,1,1,0,1196833025,R. O'Connor,R,SI,R,1.00549,2.48349,8.50748,14.15091,5.39237,F,K,-2.24971,4.97153,89.74829,2123.827816,242.194873,-0.15
3,3,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,1,2,0,1196833025,R. O'Connor,R,FA,R,0.05813,3.61215,12.69343,13.58257,5.67988,SS,K,-1.94580,5.38671,91.73254,2334.794397,229.903385,-0.15
4,4,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,0,0,1,1196833025,R. O'Connor,R,SI,L,0.94170,1.65739,7.99815,18.86064,5.39837,B,S,-2.31540,5.04714,89.11913,2173.493946,250.325904,0.13

In [20]:
# Normalize all metrics to be from pitcher's perspective
df["plateLocX"] = -df["plateLocX"]
df["relX"] = -df["relX"]

In [21]:
df.head()

,Unnamed: 0,year,pitchingTeamId,pitchingTeam,conference,hittingTeamId,hittingTeam,gameId,gameDate,inning,balls,strikes,outs,pitcherId,Pitcher,pitcherHand,pitchType,batterHand,plateLocX,plateLocZ,inducedVertBreak,horzBreak,extension,pitchResult,atbatResult,relX,relZ,releaseVelocity,spinRate,spinDir,rv
0,0,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,0,0,0,1196833025,R. O'Connor,R,SI,R,-0.49434,2.52535,5.98516,14.86544,5.56639,SL,K,2.17982,4.97129,89.08355,2069.619596,251.856227,-0.15
1,1,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,0,1,0,1196833025,R. O'Connor,R,FC,R,-1.93029,2.56696,2.29658,-0.51043,5.72107,B,K,1.96659,5.40817,87.28152,2438.897149,157.768823,0.13
2,2,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,1,1,0,1196833025,R. O'Connor,R,SI,R,-1.00549,2.48349,8.50748,14.15091,5.39237,F,K,2.24971,4.97153,89.74829,2123.827816,242.194873,-0.15
3,3,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,1,2,0,1196833025,R. O'Connor,R,FA,R,-0.05813,3.61215,12.69343,13.58257,5.67988,SS,K,1.94580,5.38671,91.73254,2334.794397,229.903385,-0.15
4,4,2026,343,NE,D1 Coastal Athletic Association,730187776,CAMP,386539296,2026-05-24 14:07:00,1,0,0,1,1196833025,R. O'Connor,R,SI,L,-0.94170,1.65739,7.99815,18.86064,5.39837,B,S,2.31540,5.04714,89.11913,2173.493946,250.325904,0.13

In [22]:
# Create fastball velo column, which takes the average velo for a pitcher's FF, SI, and FC for each season - to be used for Breaking Ball and Offspeed models
fb_velo = (
    df[df["pitchType"].isin(["FA", "SI", "FC"])]
    .groupby(["pitcherId", "year"])["releaseVelocity"]
    .mean()
    .reset_index(name="fb_velo")
)

df1 = df.merge(fb_velo, on=["pitcherId", "year"], how="left")

In [23]:
df1["pitchType"].unique()

array(['SI', 'FC', 'FA', 'CH', 'SL', 'CU', 'FS', 'ST', 'KN', 'IN'],
      dtype=object)

In [29]:
# Assign categorical column for batter/pitcher handedness
df1["phand"] = (df1["pitcherHand"] != "L").astype(int)
df1["bhand"] = (df1["batterHand"] != "L").astype(int)

In [30]:
df1.loc[df1["pitchType"].isin(["FA", "SI"]), "pitchBucket"] = "FB"
df1.loc[df1["pitchType"].isin(["FC"]), "pitchBucket"] = "FC"
df1.loc[df1["pitchType"].isin(["CH", "FS"]), "pitchBucket"] = "OFF"
df1.loc[df1["pitchType"].isin(["SL", "ST", "CU"]), "pitchBucket"] = "BB"

In [34]:
df1 = df1.dropna()

In [36]:
# Save as parquet (will use SQL to extract rows of interest moving forward)
df1.to_parquet("full_data.parquet")